---
####################
# Initialize Setting
####################
- name: timezone setting
  file:
    src: /usr/share/zoneinfo/Asia/Tokyo
    dest: /etc/localtime
    state: link
    force: yes
  notify: 
    - restart rsyslog agent 
    - restart crond
  tags:
    - timezone

- name: copy clock from template
  copy:
    src: sysconfig/clock
    dest: /etc/sysconfig/clock
    owner: root
    group: root
    mode: 0644
  tags:
    - timezone

- name: motd.sh setting
  copy:
    src: motd.sh
    dest: /etc/profile.d/motd.sh
    owner: root
    group: root
    mode: 0755
  tags:
    - motd

- name: ntpd slew mode setting
  copy:
    src: sysconfig/ntpd
    dest: /etc/sysconfig/ntpd
    owner: root
    group: root
    mode: 0644
  notify: restart ntpd 

- name: history size setting
  blockinfile:
    dest: /etc/bashrc
    content: |
      HISTSIZE=10000
      HISTTIMEFORMAT='%Y/%m/%d %H:%M:%S '
  tags:
    - history

- name: logrotate setting
  copy:
    src: logrotate.d/
    dest: /etc/logrotate.d/
    owner: root
    group: root
    mode: 0755
  tags:
    - logrotate

- name: set swapfile path
  set_fact:
    swap_file_path: /swapfile
  tags:
    - swap

- name: exec dd command for swap
  command: dd if=/dev/zero of={{ swap_file_path }} bs=2048 count=1M
  args:
    creates: '{{ swap_file_path }}'
  tags:
    - swap

- name: wait dd command complete
  pause:
    seconds: 120
  tags:
    - swap
    
- name: set swaplfile permission
  file:
    path: '{{ swap_file_path }}'
    mode: '0600'
  tags:
    - swap

- name: check swap file
  command: file {{ swap_file_path }}
  register: swap_file_test
  tags:
    - swap

- name: make swap file
  command: mkswap {{ swap_file_path }}
  when: swap_file_test.stdout.find('swap file') == -1
  tags:
    - swap

- name: exec swapon
  command: swapon {{ swap_file_path }}
  when: ansible_swaptotal_mb < 1
  tags:
    - swap

- name: mount swap file
  mount:
    name: swap
    src: '{{ swap_file_path }}'
    fstype: swap
    opts: defaults
    passno: '0'
    dump: '0'
    state: present
  tags:
    - swap

- name: sshd disable
  service: name=sshd state=stopped enabled=no
  when: sshd is defined and sshd == "stopped"
  tags:
    - sshd
